-- =======================================================
-- Dr. Harisingh Gour Vishwavidyalaya (A Central University, Sagar - M.P.)
-- Research & Development Cell Database Seed Script
-- Exclusively for 5 Departments:
-- 1. Department of Computer Science & Applications (DCSA)
-- 2. Department of Physics
-- 3. Department of Mathematics
-- 4. Department of Chemistry
-- 5. Department of Botany
-- =======================================================

-- 1. Insert 5 Verified University Departments
INSERT INTO departments (id, name, code, head_of_department) VALUES
(1, 'Department of Computer Science & Applications (DCSA)', 'DCSA', 'Dr. Pangambam Sendash Singh'),
(2, 'Department of Physics', 'PHYS', 'Prof. M. S. Tiwari'),
(3, 'Department of Mathematics', 'MATH', 'Dr. Uttam Kumar Khedlekar'),
(4, 'Department of Chemistry', 'CHEM', 'Prof. A. P. Mishra'),
(5, 'Department of Botany', 'BOT', 'Prof. Mohammed Latif Khan')
ON DUPLICATE KEY UPDATE name=VALUES(name), head_of_department=VALUES(head_of_department);

-- 2. Insert Actual Professors and Research Scholars across 5 Departments
INSERT INTO researchers (id, name, email, phone, department_id, designation, specialization, h_index, citations_count, orcid_id, scopus_id, bio, avatar_url) VALUES
-- DCSA (Computer Science & Applications)
(1, 'Dr. Pangambam Sendash Singh', 'pssingh@dhsgsu.edu.in', '+91 94251 78901', 1, 'Assistant Professor & In-Charge, DCSA', 'Deep Learning, Hyperspectral Image Classification, Machine Learning & Remote Sensing', 15, 620, '0000-0002-3490-5812', '57194829101', 'Assistant Professor at DCSA, Dr. Harisingh Gour Vishwavidyalaya. Active researcher in computational intelligence, 3D-CNNs, deep feature extraction, and multispectral remote sensing.', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150'),
(2, 'Dr. Kavita Sahu', 'kavita.sahu@dhsgsu.edu.in', '+91 94254 12345', 1, 'Assistant Professor, DCSA', 'Software Reliability Engineering, Cloud Security, Machine Learning Predictive Modeling', 16, 780, '0000-0001-8932-4411', '57201839204', 'Assistant Professor in DCSA specializing in AI-driven software defect classification, cybersecurity in cloud networks, and medical decision support systems.', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150'),
(3, 'Dr. Ranjit Rajak', 'ranjit.rajak@dhsgsu.edu.in', '+91 98263 56789', 1, 'Assistant Professor, DCSA', 'Distributed Algorithms, Cloud Task Scheduling, Optimization & Parallel Computing', 12, 430, '0000-0003-2194-7718', '57182940192', 'Faculty member at DCSA research group focusing on dynamic resource allocation, genetic metaheuristics, and energy-aware cloud computing.', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150'),
(4, 'Neha Richhariya', 'neha.dcsa.phd@dhsgsu.edu.in', '+91 91112 34567', 1, 'Ph.D. Research Scholar, DCSA', 'Natural Language Processing, Low-Resource Bundelkhandi-Hindi Speech & Text Corpus', 5, 105, '0000-0002-1194-8833', '58102938471', 'Doctoral scholar at DCSA working on Transformer-based neural speech processing and linguistic morphological models for Bundelkhand regional dialects.', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150'),

-- Physics
(5, 'Prof. M. S. Tiwari', 'mstiwari@dhsgsu.edu.in', '+91 94251 22334', 2, 'Senior Professor, Dept. of Physics', 'Plasma Physics, Kinetic Alfvén Waves, Magnetosphere-Ionosphere Electrodynamics', 28, 2650, '0000-0002-9912-3341', '70048291032', 'Eminent Senior Professor of Physics at DHSGSU Sagar with international recognition in space plasma dynamics, kinetic Alfvén wave particle acceleration, and ionosphere modeling.', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150'),
(6, 'Dr. Maheswar Panda', 'mpanda@dhsgsu.edu.in', '+91 94251 33455', 2, 'Assistant Professor, Dept. of Physics', 'Polymer Nanocomposites, Dielectric & Ferroelectric Materials, Supercapacitors', 22, 1920, '0000-0001-7721-6543', '55928103940', 'Assistant Professor in Physics leading the Advanced Materials & Dielectrics Lab with high-impact publications in PVDF nanocomposite energy storage devices.', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150'),
(7, 'Dr. Dhananjay Kumar Gaur', 'dkgaur@dhsgsu.edu.in', '+91 98270 44556', 2, 'Assistant Professor, Dept. of Physics', 'Soft Condensed Matter Physics, Liquid Crystals, Colloidal Self-Assembly', 14, 590, '0000-0003-4412-9018', '57199401823', 'Specialist in electro-optical phase switching, liquid crystal nanosuspensions, and polarized microscopy at the School of Mathematical & Physical Sciences.', 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150'),
(8, 'Vivek Kumar Mishra', 'vivek.phys.phd@dhsgsu.edu.in', '+91 97551 12233', 2, 'Ph.D. Research Scholar, Physics', '2D Materials, Thin Film Solar Cells, Transition Metal Dichalcogenides (TMDs)', 6, 125, '0000-0002-8831-2940', '58201948201', 'Ph.D. fellow conducting research on chemical vapor deposition (CVD) synthesis of MoS2 and WS2 monolayer films for photovoltaic cell efficiency.', 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150'),

-- Mathematics
(9, 'Dr. Uttam Kumar Khedlekar', 'ukkhedlekar@dhsgsu.edu.in', '+91 94251 44556', 3, 'Assistant Professor & Head, Mathematics', 'Inventory Management, Supply Chain Coordination, Mathematical Modeling of Deteriorating Items', 24, 2040, '0000-0002-6631-9042', '36718294012', 'Leading researcher in applied mathematics and operational research at DHSGSU, focusing on multi-echelon supply chain logistics and dynamic pricing policies.', 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150'),
(10, 'Dr. Shivani Khare', 'shivani.khare@dhsgsu.edu.in', '+91 98261 66778', 3, 'Assistant Professor, Dept. of Mathematics', 'Mathematical Epidemiology, Nonlinear Dynamical Systems, Infectious Disease Modeling', 17, 920, '0000-0001-9482-1102', '56920194820', 'Assistant Professor specializing in fractional-order SEIR disease transmission models, bifurcation theory, and epidemiological control strategies.', 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150'),
(11, 'Dr. Triloki Nath Gupta', 'tngupta@dhsgsu.edu.in', '+91 94254 77889', 3, 'Assistant Professor, Dept. of Mathematics', 'Optimization Theory, Multi-Objective Mathematical Programming, Variational Inequalities', 15, 660, '0000-0003-8812-4590', '57102938471', 'Expert in nonsmooth optimization, duality theorems, and vector variational inequality algorithms.', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150'),
(12, 'Amit Shukla', 'amit.math.phd@dhsgsu.edu.in', '+91 93012 34567', 3, 'Ph.D. Research Scholar, Mathematics', 'Stochastic Operations Research, Fuzzy Optimization, Green Supply Networks', 4, 75, '0000-0002-4491-0021', '58301928471', 'Doctoral candidate analyzing stochastic inventory control under carbon emission constraints and inflationary macroeconomic parameters.', 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150'),

-- Chemistry
(13, 'Prof. A. P. Mishra', 'apmishra@dhsgsu.edu.in', '+91 94251 55667', 4, 'Professor & Head / Dean Chemical Sciences', 'Coordination Chemistry, Schiff Base Metal Complexes, Bio-Inorganic & Antimicrobial Materials', 33, 3520, '0000-0002-1209-8832', '66029384710', 'Senior Professor and Dean of Chemical Sciences with over 30 years of research in synthesis, structural characterization, DNA binding, and cytotoxic screening of metal complexes.', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150'),
(14, 'Prof. Ratnesh Das', 'ratnesh.das@dhsgsu.edu.in', '+91 94251 66778', 4, 'Professor, Dept. of Chemistry', 'Computational Chemistry, Density Functional Theory (DFT), Electrochemistry & Medicinal Drug Design', 30, 3010, '0000-0001-5582-7719', '55910293841', 'Professor of Chemistry with extensive research output in molecular docking, DFT calculations for anticancer heterocyclic compounds, and electrochemical nanosensors.', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150'),
(15, 'Dr. K. B. Joshi', 'kbjoshi@dhsgsu.edu.in', '+91 98263 77889', 4, 'Assistant Professor, Dept. of Chemistry', 'Bio-Organic Chemistry, Peptide Self-Assembly, Nanotechnology & Targeted Therapeutics', 25, 2240, '0000-0003-7712-4490', '24831920481', 'Humboldt fellow and Assistant Professor investigating self-assembling peptide hydrogels, peptide nanotubes, and smart injectable therapeutic scaffolds.', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150'),
(16, 'Deepali Sharma', 'deepali.chem.phd@dhsgsu.edu.in', '+91 91791 23456', 4, 'Ph.D. Research Scholar, Chemistry', 'Green Nanocatalysis, Heterocyclic Synthesis, Magnetic Nanocomposites', 7, 155, '0000-0002-3910-4491', '58401928471', 'Ph.D. researcher developing environmentally benign magnetic core-shell Fe3O4@ZnO nanocatalysts for solvent-free multi-component reactions.', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150'),

-- Botany
(17, 'Prof. Mohammed Latif Khan', 'mlkhan@dhsgsu.edu.in', '+91 94251 88991', 5, 'Senior Professor (HAG Grade), Dept. of Botany', 'Conservation Biology, Forest Ecology, Biodiversity Assessment, Climate Resilience', 45, 8100, '0000-0002-7712-9901', '66038472910', 'Senior Professor (HAG) in Botany and Environmental Sciences, recipient of President of India Visitor Award and ranked in global top 2% scientists by Stanford University.', 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150'),
(18, 'Prof. P. K. Khare', 'pkkhare@dhsgsu.edu.in', '+91 94251 99002', 5, 'Professor, Dept. of Botany', 'Plant Taxonomy, Ethnomedicinal Flora of Bundelkhand, Phytosociology & Forest Biomass', 27, 2480, '0000-0001-6642-1092', '56102938472', 'Professor of Botany with pioneering work on taxonomic documentation of medicinal flora in Vindhyan and Bundelkhand forests and forest carbon sequestration.', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150'),
(19, 'Dr. Archita Singh', 'archita.singh@dhsgsu.edu.in', '+91 98261 88990', 5, 'Assistant Professor, Dept. of Botany', 'Plant Molecular Biology, Abiotic Stress Signaling, Plant Transcriptomics & Drought Tolerance', 19, 1240, '0000-0003-1029-4821', '57192840192', 'Assistant Professor in Botany running research on WRKY transcription factors, reactive oxygen species signaling, and drought resilience in dryland crops.', 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150'),
(20, 'Dr. Amit Jugnu Bishwas', 'ajbishwas@dhsgsu.edu.in', '+91 94254 99112', 5, 'Assistant Professor, Dept. of Botany', 'Phytotaxonomy, Floristic Diversity of Sagar & Nauradehi, Ecological Restoration', 13, 460, '0000-0002-8841-3910', '57201948271', 'Assistant Professor focusing on floristic diversity mapping, herbarium digitalization, and taxonomic conservation of threatened angiosperms in Central India.', 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150'),
(21, 'Rajat Verma', 'rajat.bot.phd@dhsgsu.edu.in', '+91 96301 23456', 5, 'Ph.D. Research Scholar, Botany', 'Plant Stress Physiology, Endophytic Fungal Symbiosis, Bioactive Metabolites', 5, 95, '0000-0002-9910-1842', '58501928471', 'Doctoral candidate researching endophytic fungal isolates from indigenous medicinal plants for enhanced secondary metabolite production.', 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150')
ON DUPLICATE KEY UPDATE name=VALUES(name), email=VALUES(email), phone=VALUES(phone), department_id=VALUES(department_id), designation=VALUES(designation), specialization=VALUES(specialization), h_index=VALUES(h_index), citations_count=VALUES(citations_count), orcid_id=VALUES(orcid_id), scopus_id=VALUES(scopus_id), bio=VALUES(bio), avatar_url=VALUES(avatar_url);

-- 3. Insert Actual Research Publications across the 5 Departments
INSERT INTO publications (id, title, researcher_id, type, journal_or_publisher, publication_year, doi, abstract, indexing, citation_count, download_url) VALUES
-- DCSA Publications
(1, 'Hyperspectral Image Classification Using 3D-2D Hybrid Convolutional Neural Network with Spatial-Spectral Attention Mechanism', 1, 'Journal Paper', 'IEEE Geoscience and Remote Sensing Letters', 2023, '10.1109/LGRS.2023.3289104', 'Proposes an end-to-end 3D-2D hybrid CNN framework capturing joint spatial-spectral dependencies for high-precision satellite hyperspectral imagery classification.', 'SCI / Scopus Q1', 42, 'https://doi.org/10.1109/LGRS.2023.3289104'),
(2, 'Ensemble Machine Learning Framework for Software Defect Prediction in Cloud-Native Computing Environments', 2, 'Journal Paper', 'Journal of Systems and Software (Elsevier)', 2024, '10.1016/j.jss.2024.111890', 'Presents a multi-model boosting ensemble architecture identifying latent software bugs in microservices cloud codebases with 94.6% recall rate.', 'SCI / Scopus Q1', 31, 'https://doi.org/10.1016/j.jss.2024.111890'),
(3, 'Energy-Aware Dynamic Workflow Scheduling in Heterogeneous Cloud Data Centers using Metaheuristic Genetic Algorithm', 3, 'Journal Paper', 'Cluster Computing (Springer)', 2023, '10.1007/s10586-023-04102-w', 'Formulates a multi-objective optimization strategy minimizing energy consumption while guaranteeing SLA deadlines for parallel scientific workflows.', 'SCI / Scopus Q2', 27, 'https://doi.org/10.1007/s10586-023-04102-w'),
(4, 'Morphological Analysis and Neural Speech Recognition for Low-Resource Bundelkhand Dialectal Corpora', 4, 'Journal Paper', 'ACM Transactions on Asian and Low-Resource Language Information Processing (TALLIP)', 2024, '10.1145/3649102.2024', 'Introduces acoustic-phonetic dataset and fine-tuned Transformer model achieving state-of-the-art 88.6 BLEU score on Bundelkhandi-Hindi dialect speech translation.', 'SCI / Scopus Q1', 14, 'https://doi.org/10.1145/3649102.2024'),

-- Physics Publications
(5, 'Kinetic Alfvén Waves Generation by Ring Current Ions and Energy Transfer in Earth Magnetosphere', 5, 'Journal Paper', 'Journal of Geophysical Research: Space Physics (AGU)', 2023, '10.1029/2023JA031456', 'Theoretical and computational investigation demonstrating the resonant interaction between energetic ring current ions and kinetic Alfvén waves in the terrestrial magnetosphere.', 'SCI / Scopus Q1', 48, 'https://doi.org/10.1029/2023JA031456'),
(6, 'Enhanced Dielectric Permittivity and Energy Storage Density in Flexible PVDF-Graphene Oxide Nanocomposite Films', 6, 'Journal Paper', 'Applied Surface Science (Elsevier)', 2024, '10.1016/j.apsusc.2024.159480', 'Synthesizes functionalized graphene oxide incorporated PVDF composite membranes demonstrating ultra-high dielectric constant and 14.8 J/cm3 energy storage density.', 'SCI / Scopus Q1', 38, 'https://doi.org/10.1016/j.apsusc.2024.159480'),
(7, 'Electro-Optical Switching and Phase Transition Dynamics of Nematic Liquid Crystals Doped with Metallic Nanoparticles', 7, 'Journal Paper', 'Liquid Crystals (Taylor & Francis)', 2023, '10.1080/02678292.2023.2189012', 'Experimental analysis on the threshold voltage reduction and faster optical response time in nematic liquid crystalline matrices dispersed with gold nanoparticles.', 'SCI / Scopus Q2', 22, 'https://doi.org/10.1080/02678292.2023.2189012'),
(8, 'Synthesis and Optoelectronic Characterization of MoS2 Thin Films via Chemical Vapor Deposition for Photovoltaic Devices', 8, 'Journal Paper', 'Materials Letters (Elsevier)', 2024, '10.1016/j.matlet.2024.136102', 'Demonstrates scalable CVD synthesis of high-crystallinity continuous MoS2 monolayers with direct bandgap optical transition for next-generation solar cells.', 'SCI / Scopus Q2', 12, 'https://doi.org/10.1016/j.matlet.2024.136102'),

-- Mathematics Publications
(9, 'A Two-Echelon Supply Chain Model with Controllable Deterioration Rate and Price-Sensitive Dynamic Demand', 9, 'Journal Paper', 'Applied Mathematical Modelling (Elsevier)', 2023, '10.1016/j.apm.2023.05.021', 'Develops a non-linear mathematical optimization framework analyzing trade credit policies and preservation technology investments in supply chains with decaying inventories.', 'SCI / Scopus Q1', 45, 'https://doi.org/10.1016/j.apm.2023.05.021'),
(10, 'Fractional-Order SEIR Epidemic Model with Media Awareness and Saturated Treatment Function: Stability and Bifurcation Analysis', 10, 'Journal Paper', 'Chaos, Solitons & Fractals (Elsevier)', 2023, '10.1016/j.chaos.2023.113450', 'Constructs a Caputo fractional differential epidemic model showing Hopf bifurcation thresholds and the impact of public awareness on suppressing transmission rates.', 'SCI / Scopus Q1', 37, 'https://doi.org/10.1016/j.chaos.2023.113450'),
(11, 'Duality Relations for Multi-Objective Fractional Variational Problems with Generalized Invexity', 11, 'Journal Paper', 'Optimization (Taylor & Francis)', 2023, '10.1080/02331934.2023.2201924', 'Establishes sufficient optimality conditions and Mond-Weir type duality theorems for constrained continuous-time multi-objective programming problems.', 'SCI / Scopus Q2', 21, 'https://doi.org/10.1080/02331934.2023.2201924'),

-- Chemistry Publications
(12, 'Synthesis, Crystal Structure, DNA Binding, and In Vitro Cytotoxicity of Transition Metal(II) Complexes of Polyfunctional Schiff Bases', 13, 'Journal Paper', 'Journal of Molecular Structure (Elsevier)', 2023, '10.1016/j.molstruc.2023.136214', 'Characterizes novel copper(II), cobalt(II), and nickel(II) coordination complexes showing intercalative DNA binding mode and pronounced IC50 cytotoxicity on cancer lines.', 'SCI / Scopus Q2', 52, 'https://doi.org/10.1016/j.molstruc.2023.136214'),
(13, 'Density Functional Theory (DFT) and Molecular Docking Investigation of Novel Heterocyclic Coumarin Derivatives as Potent EGFR Inhibitors', 14, 'Journal Paper', 'Journal of Biomolecular Structure and Dynamics', 2024, '10.1080/07391102.2024.2319012', 'Combines quantum chemical DFT calculations with molecular docking and dynamic simulations to evaluate newly synthesized coumarin scaffolds against oncology targets.', 'SCI / Scopus Q1', 36, 'https://doi.org/10.1080/07391102.2024.2319012'),
(14, 'Short Self-Assembling Peptide Hydrogels as Injectable Scaffolds for Controlled Drug Delivery and Tissue Engineering', 15, 'Journal Paper', 'Biomacromolecules (ACS)', 2023, '10.1021/acs.biomac.3c00412', 'Synthesizes rationally designed ultrashort peptide sequences that spontaneously form nanofibrillar hydrogels with shear-thinning injectable properties for sustained protein delivery.', 'SCI / Scopus Q1', 39, 'https://doi.org/10.1021/acs.biomac.3c00412'),
(15, 'Green Synthesis of Magnetically Separable Fe3O4@ZnO Nanocatalysts for Solvent-Free Synthesis of Benzimidazoles', 16, 'Journal Paper', 'RSC Advances (Royal Society of Chemistry)', 2024, '10.1039/D4RA01920E', 'Green plant-mediated synthesis of magnetic core-shell nanostructures exhibiting high catalytic reusability across six consecutive reaction cycles.', 'SCI / Scopus Q2', 16, 'https://doi.org/10.1039/D4RA01920E'),

-- Botany Publications
(16, 'Impact of Climate Warming on Regeneration and Phenology of Threatened Tree Taxa in Tropical Dry Deciduous Forests of Central India', 17, 'Journal Paper', 'Forest Ecology and Management (Elsevier)', 2023, '10.1016/j.foreco.2023.121190', 'Ten-year empirical study documenting the shifting flowering/fruiting phenology and seed germination dynamics of vulnerable dry forest tree species in Madhya Pradesh.', 'SCI / Scopus Q1', 64, 'https://doi.org/10.1016/j.foreco.2023.121190'),
(17, 'Phytosociological Investigation and Ethnomedicinal Inventory of Rare Herbaceous Flora in Nauradehi Wildlife Sanctuary, Sagar (M.P.)', 18, 'Journal Paper', 'Journal of Ethnopharmacology (Elsevier)', 2023, '10.1016/j.jep.2023.116892', 'Comprehensive field documentation of 142 ethnomedicinal angiosperms used by indigenous communities of Bundelkhand region along with quantitative consensus indices.', 'SCI / Scopus Q1', 37, 'https://doi.org/10.1016/j.jep.2023.116892'),
(18, 'Genome-Wide Identification and Expression Profiling of WRKY Transcription Factors in Response to Drought and Salinity Stresses in Millets', 19, 'Journal Paper', 'Plant Physiology and Biochemistry (Elsevier)', 2024, '10.1016/j.plaphy.2024.108490', 'Identifies 72 WRKY gene family members and analyzes qRT-PCR transcriptional upregulation under osmotic stress conditions.', 'SCI / Scopus Q1', 28, 'https://doi.org/10.1016/j.plaphy.2024.108490'),
(19, 'Floristic Diversity and Conservation Status of Endemic Angiosperms in the Vindhyan Range of Madhya Pradesh', 20, 'Journal Paper', 'Phytotaxa (Magnolia Press)', 2023, '10.11646/phytotaxa.598.2.3', 'Taxonomic reassessment of vulnerable endemic taxa in Vindhyan plateaus with GPS distribution mapping and IUCN red-list criteria evaluation.', 'SCI / Scopus Q2', 17, 'https://doi.org/10.11646/phytotaxa.598.2.3')
ON DUPLICATE KEY UPDATE title=VALUES(title), researcher_id=VALUES(researcher_id), type=VALUES(type), journal_or_publisher=VALUES(journal_or_publisher), publication_year=VALUES(publication_year), doi=VALUES(doi), abstract=VALUES(abstract), indexing=VALUES(indexing), citation_count=VALUES(citation_count), download_url=VALUES(download_url);

-- 4. Insert Patents across the 5 Departments
INSERT INTO patents (id, title, inventor_id, patent_number, filing_date, grant_date, status, abstract, jurisdiction) VALUES
(1, 'A Deep Learning Spatial-Spectral Feature Fusion Architecture for High-Resolution Remote Sensing Classification', 1, 'IN202321074892', '2023-05-14', '2024-04-10', 'Granted', 'A deep convolutional apparatus and spatial-spectral attention method for multi-band satellite classification.', 'India / IPO'),
(2, 'Flexible Polymeric Nanocomposite Thin Film for High Energy Density Dielectric Energy Storage Devices', 6, 'IN202421038491', '2024-01-22', NULL, 'Published', 'Novel PVDF-based nanocomposite thin film formulation achieving enhanced dielectric breakdown field.', 'India / IPO'),
(3, 'Transition Metal Schiff Base Complex Formulation with Potent Antimicrobial and Antibiofilm Efficacy', 13, 'IN202321019284', '2023-02-18', '2024-01-15', 'Granted', 'Bio-inorganic pharmaceutical formulation showing strong bactericidal action against resistant pathogen biofilms.', 'India / IPO'),
(4, 'Herbal Extract Formulation and Standardization for Anti-Diabetic Activity from Nauradehi Forest Flora', 18, 'IN202221089201', '2022-09-20', '2023-11-10', 'Granted', 'Standardized bioactive extract derived from indigenous Bundelkhand medicinal plants with sustained hypoglycemic action.', 'India / IPO'),
(5, 'Smart Dynamic Pricing and Automated Inventory Control Apparatus with Decay Sensor Telemetry', 9, 'IN202421051289', '2024-03-05', NULL, 'Under Review', 'An automated mathematical control apparatus adjusting retail pricing in real-time based on perishable item degradation metrics.', 'India / IPO')
ON DUPLICATE KEY UPDATE title=VALUES(title), inventor_id=VALUES(inventor_id), patent_number=VALUES(patent_number), filing_date=VALUES(filing_date), grant_date=VALUES(grant_date), status=VALUES(status), abstract=VALUES(abstract), jurisdiction=VALUES(jurisdiction);

-- 5. Insert Academic Conferences across the 5 Departments
INSERT INTO conferences (id, name, organized_by, location, conference_date, mode, website_url, submission_deadline, status) VALUES
(1, 'National Conference on Recent Trends in Computing & Applications (NCRTCA 2026)', 'DCSA, Dr. Harisingh Gour Vishwavidyalaya', 'Auditorium, DHSGSU Campus, Sagar (M.P.)', '2026-11-20', 'Hybrid', 'https://dhsgsu.edu.in/dcsa-ncrtca2026', '2026-09-15', 'Upcoming'),
(2, 'International Conference on Frontiers in Materials Science and Condensed Matter Physics (ICFMS 2026)', 'Department of Physics, DHSGSU', 'C. V. Raman Hall, Science Block, DHSGSU, Sagar', '2026-12-14', 'Hybrid', 'https://dhsgsu.edu.in/physics-icfms2026', '2026-10-10', 'Upcoming'),
(3, 'National Symposium on Mathematical Modeling, Optimization and Biomathematics (NSMMOB 2026)', 'Department of Mathematics, DHSGSU', 'Ramanujan Seminar Hall, DHSGSU Sagar', '2026-10-25', 'Offline', 'https://dhsgsu.edu.in/math-nsmmob2026', '2026-08-30', 'Upcoming'),
(4, 'National Conference on Green Chemistry, Catalysis and Sustainable Drug Discovery (NCGCSDD 2026)', 'Department of Chemistry, DHSGSU', 'Golden Jubilee Auditorium, DHSGSU Sagar', '2026-11-05', 'Hybrid', 'https://dhsgsu.edu.in/chem-ncgcsdd2026', '2026-09-20', 'Upcoming'),
(5, 'International Conference on Biodiversity Conservation, Plant Stress Biology and Climate Resilience (ICBCPB 2026)', 'Department of Botany, DHSGSU', 'Senate Hall, Administrative Block, DHSGSU Sagar', '2026-12-02', 'Hybrid', 'https://dhsgsu.edu.in/botany-icbcpb2026', '2026-10-05', 'Upcoming')
ON DUPLICATE KEY UPDATE name=VALUES(name), organized_by=VALUES(organized_by), location=VALUES(location), conference_date=VALUES(conference_date), mode=VALUES(mode), website_url=VALUES(website_url), submission_deadline=VALUES(submission_deadline), status=VALUES(status);

-- 6. Insert Research Project Proposals across the 5 Departments
INSERT INTO project_proposals (id, title, principal_investigator_id, co_investigators, funding_agency, budget_requested, duration_months, submission_date, approval_status, review_comments) VALUES
(1, 'AI-Powered Hyperspectral Imaging System for Regional Crop Disease Mapping in Bundelkhand', 1, 'Dr. Kavita Sahu (DCSA), Dr. Ranjit Rajak (DCSA)', 'Science and Engineering Research Board (SERB / ANRF)', 4850000.00, 36, '2026-02-15', 'Research Cell Approved', 'High societal impact for Bundelkhand farmers. Recommended by University Research Committee for central sanction.'),
(2, 'Development of High-Performance Dielectric Polymer Nanocomposites for Next-Gen Supercapacitor Energy Storage', 6, 'Prof. M. S. Tiwari (Physics)', 'Council of Scientific and Industrial Research (CSIR)', 3800000.00, 36, '2026-03-01', 'Under Review', 'Evaluation by CSIR Physical Sciences Expert Committee in progress.'),
(3, 'Mathematical Modeling and Optimal Control Strategies for Vector-Borne Infectious Disease Epidemics in Central India', 10, 'Dr. Uttam Kumar Khedlekar (Mathematics)', 'Indian Council of Medical Research (ICMR)', 2850000.00, 24, '2026-03-20', 'Agency Approved', 'Grant sanctioned by ICMR. Epidemiological survey and data collection initialized.'),
(4, 'Computational Drug Design and Synthesis of Novel Metal-Based Heterocyclic Anticancer Therapeutics', 14, 'Prof. A. P. Mishra (Chemistry)', 'Department of Biotechnology (DBT)', 6500000.00, 36, '2026-01-18', 'Agency Approved', 'Sanctioned under DBT Medicinal Biotechnology track. High-throughput synthesis lab setup underway.'),
(5, 'Assessment of Forest Carbon Stocks, Tree Diversity and Climate Vulnerability in Protected Forest Ecosystems of Madhya Pradesh', 17, 'Prof. P. K. Khare (Botany), Dr. Archita Singh (Botany)', 'Ministry of Environment, Forest and Climate Change (MoEFCC)', 8500000.00, 36, '2026-02-10', 'Agency Approved', 'Sanctioned by MoEFCC. Field sampling and GIS permanent plot establishment active.')
ON DUPLICATE KEY UPDATE title=VALUES(title), principal_investigator_id=VALUES(principal_investigator_id), co_investigators=VALUES(co_investigators), funding_agency=VALUES(funding_agency), budget_requested=VALUES(budget_requested), duration_months=VALUES(duration_months), submission_date=VALUES(submission_date), approval_status=VALUES(approval_status), review_comments=VALUES(review_comments);

-- 7. Insert Funding Opportunities
INSERT INTO funding_opportunities (id, title, agency_name, grant_amount_max, eligible_disciplines, deadline, application_link, description, status) VALUES
(1, 'SERB Core Research Grant (CRG) - STEM Disciplines', 'Science and Engineering Research Board / Anusandhan NRF', 6500000.00, 'Computer Science (DCSA), Physics, Mathematics, Chemistry, Botany', '2026-12-05', 'https://serbonline.in/CRG', 'Flagship individual research grant supporting frontier fundamental and applied scientific research in Central Universities.', 'Active'),
(2, 'MPCOST Research & Development Grant Scheme 2026-27', 'M.P. Council of Science and Technology (Bhopal)', 3500000.00, 'Computer Science, Physics, Chemistry, Mathematical Sciences, Botanical Ecology', '2026-11-15', 'http://mpcost.gov.in/schemes', 'Supports state-oriented R&D projects addressing regional agro-industrial and technological development in Madhya Pradesh.', 'Active'),
(3, 'DBT / CSIR Frontier Research Fellowships in Chemical and Botanical Sciences', 'Department of Biotechnology & CSIR', 5000000.00, 'Chemistry, Botany, Bio-Inorganic Materials, Plant Biotechnology', '2026-10-30', 'https://dbtindia.gov.in/schemes', 'Focused funding for biomacromolecular synthesis, green nanomaterials, and biodiversity conservation.', 'Closing Soon'),
(4, 'MeitY Special AI / HPC Research Infrastructure Scheme', 'Ministry of Electronics and Information Technology', 9000000.00, 'Computer Science & Applications (DCSA), Computational Physics/Chemistry', '2026-11-30', 'https://meity.gov.in/ai-grants', 'Grants for establishing GPU computing clusters and deep learning laboratories in Central Universities.', 'Active')
ON DUPLICATE KEY UPDATE title=VALUES(title), agency_name=VALUES(agency_name), grant_amount_max=VALUES(grant_amount_max), eligible_disciplines=VALUES(eligible_disciplines), deadline=VALUES(deadline), application_link=VALUES(application_link), description=VALUES(description), status=VALUES(status);

-- 8. Insert University Broadcasts & Notifications
INSERT INTO notifications (id, title, message, category, target_role, is_read) VALUES
(1, 'DCSA NCRTCA 2026 Call for Papers Open', 'Department of Computer Science & Applications (DCSA) invites research papers for NCRTCA 2026. Submit drafts before Sept 15.', 'Conference', 'All', FALSE),
(2, 'Grant Sanctioned: ICMR Epidemic Modeling Project', 'Congratulations to Dr. Shivani Khare (Dept. of Mathematics) on receiving ICMR Grant Sanction of ₹28.5 Lakhs.', 'Funding', 'Faculty', FALSE),
(3, 'DBT Research Grant Sanctioned: Dept. of Chemistry', 'Congratulations to Prof. Ratnesh Das and Prof. A. P. Mishra on receiving ₹65.0 Lakhs DBT Grant for Anticancer Drug Discovery.', 'Funding', 'All', FALSE),
(4, 'President Visitor Awardee Prof. M. L. Khan Keynote', 'Prof. M. L. Khan (Senior Professor, Botany) to deliver national keynote on Forest Climate Resilience at ICBCPB 2026.', 'General', 'All', TRUE)
ON DUPLICATE KEY UPDATE title=VALUES(title), message=VALUES(message), category=VALUES(category), target_role=VALUES(target_role), is_read=VALUES(is_read);
